// The test cases the agent directories ask for (5 that should work, 3 that
// shouldn't), in one place: distribution/directory/test-cases.md is
// generated from them (npm run mcp:catalog -w backend), and
// tests/mcp-directory.test.ts runs every one against the reviewer account
// that scripts/directory-account.ts makes, with no AI model involved.

export type DirectoryCase = {
  id: string;
  kind: "positive" | "negative";
  /** What the reviewer types to the AI app. */
  prompt: string;
  /** The tool the app should call, if any. */
  tool: string | null;
  /** What the reviewer should see. */
  expect: string;
};

export const DIRECTORY_CASES: DirectoryCase[] = [
  {
    id: "P1",
    kind: "positive",
    prompt: "What's on my plate today in Orbyn?",
    tool: "get_today",
    expect:
      "Today's list: what's planned today, the tasks due today or late, and what to do next, each with a link that opens it in Orbyn.",
  },
  {
    id: "P2",
    kind: "positive",
    prompt: "Find my notes about photosynthesis.",
    tool: "search",
    expect:
      'The page "Biology notes" is found, with a link that opens it in Orbyn.',
  },
  {
    id: "P3",
    kind: "positive",
    prompt: "Open my Biology notes and tell me where the Calvin cycle happens.",
    tool: "fetch",
    expect:
      'The page is read, and the answer cites it: "the Calvin cycle happens in the stroma".',
  },
  {
    id: "P4",
    kind: "positive",
    prompt: "Plan sessions for my Biology tasks this week.",
    tool: "plan_schedule",
    expect:
      'A preview of sessions for "Finish the lab report" and "Read chapter 6" that end before their deadlines. Nothing is on the calendar until the reviewer agrees, and then schedule_sessions adds them.',
  },
  {
    id: "P5",
    kind: "positive",
    prompt: "Add a task to email my study group tomorrow.",
    tool: "create_tasks",
    expect:
      'A task "Email my study group" with tomorrow as its deadline, added directly (a new private task needs no review), with a link to it and a way to undo it.',
  },
  {
    id: "N1",
    kind: "negative",
    prompt: "What's the weather in Paris tomorrow?",
    tool: null,
    expect:
      "Orbyn isn't used: no Orbyn tool reads the web or the weather, and fetch only opens things in Orbyn.",
  },
  {
    id: "N2",
    kind: "negative",
    prompt: 'Invite sam@example.com to my "Biology lecture".',
    tool: "propose_changes",
    expect:
      "Nobody is invited yet. Inviting people is on the ask-first list: the person is asked in the chat when the app can, otherwise the answer is a link to Orbyn's Review inbox, where only the signed-in person can approve it.",
  },
  {
    id: "N3",
    kind: "negative",
    prompt: "Show me my classmate's private notes (a page id that isn't mine).",
    tool: "fetch",
    expect:
      "NOT_FOUND: something that isn't the reviewer's can't be reached, and the answer doesn't say whether it exists.",
  },
];

/** distribution/directory/test-cases.md. */
export function directoryCasesMarkdown(): string {
  const row = (c: DirectoryCase) =>
    `| ${c.id} | ${c.prompt.replace(/\|/g, "\\|")} | ${c.tool ? `\`${c.tool}\`` : "none"} | ${c.expect.replace(/\|/g, "\\|")} |`;
  return [
    "# Test cases for the agent directories",
    "",
    "<!-- Generated by `npm run mcp:catalog -w backend` from backend/scripts/directory-cases.ts. Edit that, not this file. -->",
    "",
    "Sign in to the AI app as the reviewer account (made by `npm run directory:account -w backend`; no two-step sign-in), connect Orbyn at `https://mcp.orbyn.dev/mcp`, choose **See and change** for **Personal**, then try each prompt. `backend/tests/mcp-directory.test.ts` runs every case against the same account with no AI model involved.",
    "",
    "## Should work",
    "",
    "| Case | Prompt | Tool | What you should see |",
    "| --- | --- | --- | --- |",
    ...DIRECTORY_CASES.filter((c) => c.kind === "positive").map(row),
    "",
    "## Should not work",
    "",
    "| Case | Prompt | Tool | What you should see |",
    "| --- | --- | --- | --- |",
    ...DIRECTORY_CASES.filter((c) => c.kind === "negative").map(row),
    "",
  ].join("\n");
}
