import { z } from "zod";

const jobId = z.uuid();
/** Private job addresses are generated by the server, never fetched from a host URL. */
export const pluginJobUri = (id: string) =>
  `orbyn://plugin-job/${jobId.parse(id)}`;

/** Bounded job/cursor resource input; no extra identity, URL or host parameters. */
export function parsePluginJobUri(
  uri: string,
): { id: string; cursor?: string } | null {
  if (typeof uri !== "string" || uri.length > 700) return null;
  try {
    const value = new URL(uri);
    const parsed = jobId.safeParse(value.pathname.slice(1));
    const cursors = value.searchParams.getAll("cursor");
    if (
      value.protocol !== "orbyn:" ||
      value.hostname !== "plugin-job" ||
      value.username ||
      value.password ||
      value.port ||
      value.hash ||
      !parsed.success ||
      cursors.length > 1 ||
      [...value.searchParams.keys()].some((key) => key !== "cursor") ||
      (cursors.length && (!cursors[0] || cursors[0].length > 512))
    )
      return null;
    return {
      id: parsed.data,
      ...(cursors.length ? { cursor: cursors[0] } : {}),
    };
  } catch {
    return null;
  }
}
