import { AGENT_ACCESS_LABELS, DEFAULT_AGENT_LIMITS } from "@orbyn/core";
import { SUSPEND_AFTER } from "../modules/mcp-server/limits.js";
import { EXCLUDED, PENDING, COVERED } from "./exclusions.js";
import { registry } from "./index.js";
import { describe, type Capability } from "./registry.js";
import { CONVENTIONS } from "./context.js";

/**
 * The published description of Orbyn's MCP server: mcp-catalog.json (a
 * snapshot every change to a tool shows up in) and docs/mcp.md (the page
 * people read), both generated from the registry by
 * `npm run mcp:catalog -w backend` and checked in CI by mcp-catalog.test.ts.
 */

/** Protocol revisions and instructions, passed in to avoid loading the SDK here. */
export type ServerFacts = {
  protocol_versions: string[];
  instructions: string;
  mcp_url: string;
};

const kindOf = (c: Capability) =>
  c.annotations.readOnlyHint
    ? "read"
    : c.annotations.destructiveHint
      ? "destructive"
      : "write";

export function buildCatalog(facts: ServerFacts) {
  return {
    server: {
      name: "orbyn",
      title: "Orbyn",
      address: facts.mcp_url,
      protocol_versions: facts.protocol_versions,
      instructions: facts.instructions,
    },
    tools: registry.all.map((c) => {
      const d = describe(c);
      return {
        name: c.name,
        title: c.title,
        description: c.description,
        kind: kindOf(c),
        access: c.access,
        toolset: c.toolset,
        mode: c.mode,
        tier: c.tier,
        ...(c.legacyOnly ? { legacy_only: true } : {}),
        ...(c.jsonText ? { json_text: true } : {}),
        annotations: d.annotations,
        input_schema: d.inputSchema,
        output_schema: d.outputSchema,
      };
    }),
    routes: {
      covered: Object.keys(COVERED).length,
      excluded: Object.keys(EXCLUDED).length,
      pending: PENDING.length,
    },
  };
}
export type Catalog = ReturnType<typeof buildCatalog>;

type Prop = {
  type?: string | string[];
  description?: string;
  enum?: unknown[];
  const?: unknown;
  format?: string;
  default?: unknown;
  items?: Prop;
  anyOf?: Prop[];
};

const FORMATS: Record<string, string> = {
  uuid: "id",
  "date-time": "ISO 8601 instant",
};

const typeText = (p: Prop): string => {
  if (p.enum) return p.enum.map((v) => `\`${String(v)}\``).join(", ");
  if (p.const !== undefined) return `\`${String(p.const)}\``;
  if (p.anyOf) return p.anyOf.map(typeText).join(" or ");
  if (p.type === "array")
    return `list of ${p.items ? typeText(p.items) : "values"}`;
  if (p.format && FORMATS[p.format]) return FORMATS[p.format];
  return Array.isArray(p.type) ? p.type.join(" or ") : (p.type ?? "any");
};

/**
 * Prose for Markdown: anything with angle brackets (task:<uuid>, the
 * untrusted-content fence) as code, so it shows instead of vanishing as HTML.
 */
const prose = (s: string) =>
  s.replace(
    /<untrusted-content[^>]*>|[^\s`]*<[^>\s]+>[^\s`,.;:]*/g,
    (m) => `\`${m}\``,
  );

/** A table cell: prose, on one line, with its pipes escaped. */
const cell = (s: string) => prose(s).replace(/\|/g, "\\|").replace(/\n/g, " ");

/** docs/mcp.md, from the catalog. */
export function catalogMarkdown(catalog: Catalog): string {
  const tools = catalog.tools.filter((t) => !t.legacy_only);
  const legacy = catalog.tools.filter((t) => t.legacy_only);
  const limits = DEFAULT_AGENT_LIMITS;
  const out: string[] = [
    "# Orbyn for AI agents (MCP)",
    "",
    "<!-- Generated by `npm run mcp:catalog -w backend` from backend/src/capabilities. Edit those, not this file. -->",
    "",
    "Orbyn is a hosted service. Outside AI agents, such as Claude Code, Codex and Cursor, can connect to it over the Model Context Protocol (MCP). An agent sees only what its person can open, in the spaces the connection was given. It uses its own model: Orbyn runs no AI for it.",
    "",
    "## Address",
    "",
    `\`${catalog.server.address}\` (Streamable HTTP, one JSON-RPC message per POST).`,
    "",
    "Older setups that use the web app's `/api/mcp` reach the same server.",
    "",
    "## Signing in",
    "",
    "- **Agent keys.** Make a key in Settings → Connected agents. Choose what it may do and which spaces it sees (Personal and any of your teams). Keys last 30 days unless you choose otherwise, and never more than 365. Send it as `Authorization: Bearer oak_…`. The key is shown once and stored only as a hash. You can revoke it at any time, and each key has its own activity list.",
    `- **Access levels.** ${Object.values(AGENT_ACCESS_LABELS)
      .map((l) => `${l.name}: ${l.blurb}`)
      .join(" ")} In phase A1 every tool reads; changes arrive in phase A3.`,
    "- **Teams.** In each team, an agent can do no more than its person's role allows. Viewers only read. Team owners and admins can cap agents in their team at suggest or read, or turn them off (only when signed in; a personal API key can't change it). Leaving a team takes it off your agent keys, and joining again doesn't give it back to them.",
    '- **Hide outside content.** A key can leave out text from outside Orbyn: subscribed calendars (shown as busy time), imported files, tasks sent by email, and what booking guests typed (their events show as "Booking"). The agent sees that something is there, not what it says. Without it, that text comes back fenced as untrusted content and labelled with where it came from; a booking guest\'s email address never shows.',
    "- **Personal API keys (`ok_`).** They keep working here as a legacy connection for 90 days from this release. Answers carry `Deprecation` and `Sunset` headers. After that they work only with the REST API and CalDAV.",
    "- **Signing in from claude.ai and ChatGPT (OAuth)** is coming in phase A2. Until then, those apps can't connect. A request with no credential gets `401` and a `WWW-Authenticate` challenge that points to the protected-resource metadata (`/.well-known/oauth-protected-resource/mcp`).",
    "- Agent credentials work only here. The REST API and CalDAV refuse them. An app sign-in (a browser session) is refused here.",
    "",
    "## Protocol",
    "",
    `- Revisions: ${catalog.server.protocol_versions.map((v) => `\`${v}\``).join(", ")}. \`2026-07-28\` is served statelessly, with \`server/discover\`, per-request \`_meta\` and the \`MCP-Protocol-Version\`, \`Mcp-Method\` and \`Mcp-Name\` header checks. A header that disagrees with the body gets \`-32020\`, and an unsupported revision gets \`-32022\` with the supported list. Both answer with HTTP 400.`,
    "- The 2025 revisions start with `initialize`, and `ping` answers. No session id is ever issued.",
    "- `GET` and `DELETE` get `405`. JSON-RPC batches are refused with `400`. Answers are JSON.",
    "- Browser pages may call only from claude.ai, chatgpt.com, vscode.dev and insiders.vscode.dev (and the MCP Inspector during local development). Other pages get `403`. Clients that send no `Origin` are fine.",
    "- `tools/list` may be cached for 5 minutes (`ttlMs`, private). Its order is stable.",
    "- `X-MCP-Toolsets` and `X-MCP-Readonly` headers can narrow a connection for one call, but never widen it.",
    "",
    "## Limits",
    "",
    "Limits count per connection, never per address. Past a limit the answer is `429` with `Retry-After` and a JSON-RPC error (`-32029`).",
    "",
    `A connection that goes over its limits more than ${SUSPEND_AFTER.limited} times, or is refused (\`NOT_FOUND\` or \`FORBIDDEN\`) more than ${SUSPEND_AFTER.denied} times, within ten minutes is paused. It gets \`403\` until its person restores it in Settings → Connected agents.`,
    "",
    "| Limit | Default |",
    "| --- | --- |",
    `| Calls a minute per connection | ${limits.calls_per_minute} |`,
    `| Searches a minute (\`search\`, \`find_passages\`) | ${limits.search_per_minute} |`,
    `| Calls a minute across one person's connections | ${limits.user_per_minute} |`,
    `| Calls in flight at once per connection | ${limits.concurrent} |`,
    `| Calls a day per connection | ${limits.calls_per_day} |`,
    `| Changes a minute / a day per connection | ${limits.writes_per_minute} / ${limits.writes_per_day} |`,
    "",
    "## Errors",
    "",
    "| When | HTTP | JSON-RPC code |",
    "| --- | --- | --- |",
    "| No credential, or one that isn't valid here | 401, with `WWW-Authenticate` | -32001 |",
    "| A disabled account, a suspended connection, a blocked app, or a page not on the list | 403 | -32003 |",
    "| Outside agents switched off by the administrator | 503, with `Retry-After` | -32002 |",
    "| Past a limit | 429, with `Retry-After` | -32029 |",
    "| Maintenance: changes are paused, reads go on | 200 | -32000 |",
    "| Not JSON / not a request / a batch | 400 | -32700 / -32600 |",
    "| `params` that isn't an object, an unknown tool | 200 | -32602 |",
    "| An unknown method | 200 or 404 | -32601 |",
    "",
    "A tool that can't do what was asked answers with `isError: true` and one of these codes, followed by a fix, so the model can correct itself. Invalid arguments come back this way too, and not as protocol errors.",
    "",
    "- `NOT_FOUND`: nothing with that id can be reached from this connection. This is also the answer when something exists but the connection can't see it, so nothing leaks.",
    "- `INVALID`: an argument is wrong. The message names the field.",
    "- `AMBIGUOUS`: several things have that title. The candidates are listed.",
    "- `FORBIDDEN`: the connection can't do this here (its access level, or a tool it lacks).",
    "- `READ_ONLY`: the administrator has paused changes by agents.",
    "- `UNAVAILABLE`: not available to agents yet.",
    "- `INTERNAL`: something went wrong on Orbyn's side. Try again.",
    "",
    "## Ids, links and content",
    "",
    `- ${prose(CONVENTIONS.ids)}`,
    `- ${prose(CONVENTIONS.links)}`,
    `- ${prose(CONVENTIONS.times)}`,
    `- ${prose(CONVENTIONS.content)}`,
    "- `search` and `fetch` follow OpenAI's contract: `search` needs only `query`, `fetch` takes `id`, and their text content is the JSON of the structured content.",
    "- Search is by words, the letters of a title, and recency. No embeddings or AI are used here.",
    "",
    "## Tools",
    "",
    "| Tool | Title | Kind | Needs |",
    "| --- | --- | --- | --- |",
    ...tools.map(
      (t) =>
        `| \`${t.name}\` | ${cell(t.title)} | ${t.kind} | ${t.access}, ${t.toolset} |`,
    ),
    "",
  ];
  for (const t of tools) {
    out.push(`### \`${t.name}\``, "", prose(t.description), "");
    const props = Object.entries(
      (t.input_schema.properties ?? {}) as Record<string, Prop>,
    );
    const required = new Set(
      (t.input_schema.required as string[] | undefined) ?? [],
    );
    if (props.length) {
      out.push("| Argument | Type | Notes |", "| --- | --- | --- |");
      for (const [name, p] of props)
        out.push(
          `| \`${name}\`${required.has(name) ? " (required)" : ""} | ${cell(typeText(p))} | ${cell(
            [
              p.description,
              p.default !== undefined
                ? `Default ${JSON.stringify(p.default)}.`
                : "",
            ]
              .filter(Boolean)
              .join(" "),
          )} |`,
        );
      out.push("");
    } else out.push("No arguments.", "");
  }
  out.push(
    "## Older tools",
    "",
    "Personal API keys on the legacy address also get the first endpoint's three tools, unchanged, until they stop working here:",
    "",
    ...legacy.map((t) => `- \`${t.name}\`: ${prose(t.description)}`),
    "",
    "## Changes",
    "",
    "Tools change only by adding: a tool is never renamed, and a field never changes its type. A tool that is going away is marked deprecated in its description first. Each change to a tool appears in `docs/mcp-catalog.json`.",
    "",
    `Routes: ${catalog.routes.covered} of the app's signed-in routes are covered by tools, ${catalog.routes.excluded} are never for agents, and ${catalog.routes.pending} are still to come.`,
    "",
  );
  return out.join("\n");
}
