/**
 * Every signed-in route of the app, and what agents can do about it: a
 * capability that covers it, an exclusion with a reason (things agents must
 * never do, or that make no sense for them), or pending (not yet reachable by
 * agents; each later phase moves routes from PENDING to COVERED). The route
 * inventory test (backend/tests/route-inventory.test.ts) checks this against
 * the routes the app really has, so a new signed-in route fails CI until it
 * is placed here, and PENDING can only shrink.
 *
 * Keys are "METHOD /route/pattern", as Fastify registers them.
 */

/** Why agents never reach a route. */
export const EXCLUSION_REASONS = {
  sign_in:
    "Signing in and how an account signs in (sessions, two-step, passkeys): people only.",
  account:
    "The account itself: name and email, public profile, privacy, consent, first-run, the email-to-task address, export and deleting the account: people only. (Planner, notice and keep-originals settings are the agent's to change since H6a: update_planner_settings.)",
  credentials:
    "Keys, webhooks, chat delivery, calendar feed links and agent connections: an agent must never mint access or send data somewhere new.",
  outside_fetch:
    "Previewing a captured link makes Orbyn fetch an outside address for the agent. (Subscribing to a calendar by link, changing its link and refreshing it are the agent's since H6a/H6b, through the app's own subscription service and its public-address check.)",
  hosted_ai:
    "Orbyn's own assistant: agents bring their own model and never spend the hosted one.",
  assistant_control:
    "Controls for the built-in assistant's own runs and approval scope: its connected agents cannot inspect or operate these.",
  people_only:
    "Approving or declining a proposal, and undoing an agent's change: only a person signed in to Orbyn can.",
  admin: "The admin console and AI provider settings.",
  internal: "Service-to-service routes, never for people or agents.",
  caldav: "CalDAV for calendar apps, signed in with a personal API key.",
  stream: "Long-lived event streams (subscriptions/listen arrives in phase 6).",
  mcp: "The MCP address itself.",
  device:
    "Devices, presence and the person's own activity (marking something opened): an agent polling isn't the person being there. (The recent list itself is get_history \"recent\" since H6b.)",
  export_file: "Files for download (PDF, Word, CSV), not data an agent needs.",
  team_admin:
    "Deleting a team, and a team's agent policy, publishing switch and policies: people only. (Making and renaming a team, members, roles and the meeting budget are asked for through organize since H6b.)",
  sends_outside: "Sends an email to test delivery.",
  kept_files:
    "Originals kept in Orbyn's file store (downloading or deleting one): people only, in the apps.",
  trash:
    "Deleting a page in the Trash for good: people only. (Listing the Trash and bringing a page back are the agent's since H6b: get_history, propose_changes.)",
  arrangement:
    "Dragging things into an order on screen (a task's place in a list): how a person lays out their own view.",
  editor_shortcut:
    "Naming a line so a link can point at it: the editor's own step; agents link to lines by their anchors (^b…).",
  file_bytes:
    "Uploading, showing and downloading pictures and files in pages through short-lived signed links: people's apps only; agents read pages as words.",
  publishing:
    "Putting a page or folder on the public web, its password, and a team's switch for it: people only, since it shows words to anyone.",
  bring_in:
    "Bringing in another app's export (a Markdown or Notion zip): people choose the file and read the dry run.",
  navigation:
    "How a person arranges their own app (stars, the sidebar, shortcuts, view choices): not data an agent needs.",
  library:
    "Tidying the library (archiving, moving or tagging several pages at once): agents file and change pages with their own page tools, under review.",
  connections_map:
    "The Connections map: a drawing of a page's or project's links for the Info panel; agents read the same links through fetch and search.",
  clipper:
    "The Orbyn Clipper browser extension's own routes, signed in with a Clipper key that works nowhere else.",
} as const;
export type ExclusionReason = keyof typeof EXCLUSION_REASONS;

/** Routes a capability already covers, with the capabilities that do. */
export const COVERED: Record<string, string[]> = {
  "GET /ai/chats": ["get_chats"],
  "GET /ai/chats/:id": ["get_chats"],
  "GET /ai/projects/:id/chats": ["get_chats"],
  "GET /search": ["search"],
  "GET /find": ["search"],
  // The link picker finds names as /find does; pills are titles and states
  // that fetch returns.
  "GET /links/pick": ["search"],
  "GET /links/resolve": ["fetch"],
  // A page's Info panel: its facts (project, tags, versions, links) that
  // fetch returns with the page.
  "GET /docs/:id/info": ["fetch"],
  "GET /items": ["query"],
  "GET /items/:id": ["fetch"],
  "GET /docs": ["query"],
  "GET /docs/:id": ["fetch"],
  "GET /docs/:id/markdown": ["fetch"],
  "GET /projects": ["query"],
  "GET /projects/:id": ["get_project", "fetch"],
  "GET /projects/:id/activity": ["get_project"],
  "GET /calendar": ["get_calendar"],
  "GET /calendar/search": ["get_calendar"],
  "GET /blocks": ["get_calendar"],
  "GET /work-records": ["query"],
  "GET /work-records/:id": ["fetch"],
  "GET /planner/next": ["get_today"],
  "GET /teams": ["get_context"],
  "GET /me": ["get_context"],
  "GET /me/goals": ["manage_goals"],
  "POST /me/goals": ["manage_goals"],
  "PUT /me/goals/:id": ["manage_goals"],
  "DELETE /me/goals/:id": ["manage_goals"],
  "GET /me/goals/:id/checkins": ["manage_goals"],
  "GET /me/agent-routines": ["manage_agent_routines"],
  "POST /me/agent-routines": ["manage_agent_routines"],
  "PUT /me/agent-routines/:id": ["manage_agent_routines"],
  "DELETE /me/agent-routines/:id": ["manage_agent_routines"],
  "GET /planner/prefs": ["get_context"],
  "GET /today": ["get_today"],
  // Merged in the M1–M4 integration and classified in A1-late.
  "GET /items/:id/context": ["fetch"],
  "GET /items/:id/sessions": ["fetch"],
  "GET /planned": ["get_today", "get_calendar"],
  "GET /agenda/:date": ["fetch", "query"],
  "GET /projects/:id/planning": ["get_project"],
  "GET /projects/:id/sessions": ["get_project"],
  // Changes (A3): the write tools, through the same services as these routes.
  "POST /items": ["create_tasks"],
  "POST /items/quick": ["create_tasks"],
  "PUT /items/:id": ["update_tasks", "complete_tasks", "link"],
  "PUT /items/:id/project": ["update_tasks", "link"],
  "DELETE /items/:id": ["propose_changes"],
  "POST /items/:id/steps": ["edit_checklist"],
  "PUT /items/:id/steps/:stepId": ["edit_checklist"],
  // The toolsets (A5): every route a signed-in person uses, reachable
  // through a tool (writes through the same services as these routes).
  "GET /docs/:id/versions/:version/changes": ["get_history"],
  "PUT /docs/:id/tags": ["organize"],
  "POST /docs/:id/tags": ["organize"],
  "GET /docs/event-notes": ["query", "fetch"],
  "POST /capture": ["create_tasks", "create_doc"],
  "GET /projects/:id/links": ["get_project"],
  "POST /projects/:id/links": ["update_project"],
  "DELETE /projects/:id/links/:linkId": ["update_project", "propose_changes"],
  "POST /projects/:id/plan": ["plan_schedule", "schedule_sessions"],
  "GET /page-templates": ["search"],
  "POST /page-templates": ["save_template"],
  "PUT /page-templates/:id": ["save_template"],
  "DELETE /page-templates/:id": ["propose_changes"],
  "POST /page-templates/from-doc/:id": ["save_template"],
  "POST /page-templates/:id/use": ["create_doc"],
  "GET /asks": ["get_follow_through"],
  "POST /asks/:id/reply": ["answer_ask"],
  "POST /asks/:id/settle": ["answer_ask"],
  "GET /availability": ["find_time"],
  "POST /blocks/:id/duplicate": ["schedule_sessions", "reschedule_sessions"],
  "GET /booking-pages": ["get_bookings"],
  "POST /booking-pages": ["booking_action"],
  "DELETE /booking-pages/:id": ["booking_action"],
  "PUT /booking-pages/:id": ["booking_action"],
  "GET /booking-pages/:id/bookings": ["get_bookings"],
  "POST /booking-pages/:id/bookings/:bookingId/cancel": ["booking_action"],
  "GET /bookings": ["get_bookings"],
  "GET /bookings/:id": ["get_bookings"],
  "POST /bookings/:id/approve": ["booking_action"],
  "POST /bookings/:id/cancel": ["booking_action"],
  "POST /bookings/:id/decline": ["booking_action"],
  "PUT /bookings/:id/no-show": ["booking_action"],
  "PUT /bookings/:id/note": ["booking_action"],
  "POST /bookings/:id/reschedule": ["booking_action"],
  "GET /bookings/:id/slots": ["get_bookings"],
  "GET /bookings/stats": ["get_bookings"],
  "GET /docs/:id/comments": ["get_history"],
  "POST /docs/:id/comments": ["comment_on_doc"],
  "DELETE /docs/:id/comments/:commentId": ["propose_changes"],
  "PUT /docs/:id/comments/:commentId": ["comment_on_doc"],
  "GET /docs/:id/people": ["comment_on_doc", "get_team"],
  "POST /docs/:id/review": ["propose_changes"],
  "GET /docs/:id/suggestions": ["get_history"],
  "DELETE /docs/:id/suggestions/:sid": ["resolve_suggestions"],
  "POST /docs/:id/suggestions/:sid": ["resolve_suggestions"],
  "POST /docs/:id/tasks": ["tasks_from_doc"],
  "GET /docs/:id/versions": ["get_history"],
  "GET /docs/:id/versions/:version": ["get_history"],
  "GET /docs/fading": ["get_follow_through"],
  "GET /favourites": ["query"],
  "PUT /favourites": ["organize", "save_view"],
  "DELETE /focus/current": ["set_focus_timer"],
  "GET /focus/current": ["get_work_patterns"],
  "PUT /focus/current": ["set_focus_timer"],
  "POST /focus/sessions": ["log_focus"],
  "GET /focus/summary": ["get_work_patterns"],
  "GET /folders": ["search"],
  "POST /folders": ["organize"],
  "DELETE /folders/:id": ["propose_changes"],
  "PUT /folders/:id": ["organize"],
  "GET /imports": ["list_imports"],
  "POST /imports": ["start_import"],
  "DELETE /imports/:id": ["cancel_import"],
  "GET /imports/:id": ["list_imports"],
  "GET /imports/capabilities": ["list_imports"],
  "GET /items/:id/ask": ["get_follow_through"],
  "POST /items/:id/note": ["create_doc"],
  "GET /items/:id/proofs": ["get_history"],
  "POST /items/:id/proofs": ["add_progress"],
  "DELETE /items/:id/proofs/:proofId": ["propose_changes"],
  "POST /items/:id/skip": ["update_tasks"],
  "POST /items/:id/time": ["log_focus"],
  "POST /items/:id/updates": ["add_progress"],
  "GET /lists": ["search"],
  "POST /lists": ["organize"],
  "DELETE /lists/:id": ["propose_changes"],
  "PUT /lists/:id": ["organize"],
  "GET /notifications": ["get_follow_through"],
  // H6a folded mark_notifications_read into ack_inbox (notices); the old
  // name still answers for connections that call it.
  "POST /notifications/:id/read": ["ack_inbox"],
  "GET /open-invites": ["get_bookings"],
  "POST /open-invites": ["booking_action"],
  "DELETE /open-invites/:id": ["booking_action"],
  "GET /open-invites/:id": ["get_bookings"],
  "GET /planner/analytics": ["get_work_patterns"],
  "GET /planner/estimates": ["get_work_patterns"],
  "GET /planner/frames": ["get_work_patterns"],
  "POST /planner/frames": ["manage_routines"],
  "DELETE /planner/frames/:id": ["propose_changes"],
  "PUT /planner/frames/:id": ["manage_routines"],
  "POST /planner/frames/:id/skip": ["manage_routines"],
  "POST /planner/frames/:id/unskip": ["manage_routines"],
  "GET /planner/habits": ["get_work_patterns"],
  "POST /planner/habits": ["manage_routines"],
  "DELETE /planner/habits/:id": ["propose_changes"],
  "PUT /planner/habits/:id": ["manage_routines"],
  "DELETE /planner/habits/blocks/:id": ["propose_changes"],
  "POST /planner/habits/plan": ["plan_schedule"],
  "POST /planner/habits/plan/apply": ["schedule_sessions"],
  "GET /planner/learning": ["get_work_patterns"],
  "GET /planner/places": ["get_work_patterns"],
  "POST /planner/places": ["manage_routines"],
  "DELETE /planner/places/:id": ["propose_changes"],
  "PUT /planner/places/:id": ["manage_routines"],
  "GET /planner/plans/:id": ["plan_schedule"],
  "PATCH /planner/plans/:id": ["plan_schedule"],
  "GET /planner/reality": ["get_work_patterns"],
  "GET /planner/review": ["get_work_patterns", "plan_schedule"],
  "POST /planner/roll-forward": ["plan_schedule", "reschedule_sessions"],
  "POST /planner/what-if": ["what_if"],
  "GET /progress": ["get_follow_through"],
  "PUT /projects/:id": ["update_project"],
  "GET /projects/:id/time-machine/:eventOrder": ["get_history"],
  "GET /projects/:id/time-machine/checkpoints": ["get_history"],
  "GET /study": ["get_study"],
  "POST /study/cards/:id/review": ["update_study"],
  "PUT /study/exams": ["update_study"],
  "GET /study/queue": ["get_study"],
  "POST /study/revision/apply": ["schedule_sessions"],
  "POST /study/revision/plan": ["plan_revision"],
  "GET /tags": ["search"],
  "POST /tags": ["organize"],
  "DELETE /tags/:id": ["propose_changes"],
  "PUT /tags/:id": ["organize"],
  "GET /teams/:id": ["get_team"],
  "GET /teams/:id/analytics": ["get_team"],
  "GET /teams/:id/attention": ["get_team"],
  "POST /teams/:id/attention/check": ["get_team", "find_time"],
  "GET /teams/:id/availability": ["find_time"],
  "GET /teams/:id/capacity": ["get_team"],
  "GET /teams/:id/suggest": ["find_time"],
  "GET /teams/:id/workload": ["get_team"],
  "GET /templates": ["search"],
  "POST /templates": ["save_template"],
  "DELETE /templates/:id": ["propose_changes"],
  "PUT /templates/:id": ["save_template"],
  "POST /templates/:id/use": ["create_project"],
  "POST /templates/from-project/:id": ["save_template"],
  "POST /work-records": ["save_record"],
  "PUT /work-records/:id": ["save_record"],
  "GET /work-records/:id/evidence": ["get_follow_through"],
  "POST /work-records/:id/respond": ["save_record"],
  "POST /me/import": ["import_tasks"],
  "DELETE /items/:id/steps/:stepId": ["propose_changes"],
  "POST /blocks": ["schedule_sessions"],
  "PUT /blocks/:id": ["reschedule_sessions"],
  "POST /blocks/:id/reschedule": ["reschedule_sessions"],
  "DELETE /blocks/:id": ["reschedule_sessions"],
  "POST /planner/preview": ["plan_schedule"],
  "POST /planner/plans/:id/apply": ["schedule_sessions"],
  "GET /planner/plans/:id/stale": ["schedule_sessions"],
  "POST /docs": ["create_doc"],
  "PUT /docs/:id": ["edit_doc", "link"],
  "POST /docs/:id/suggestions": ["edit_doc"],
  "DELETE /docs/:id": ["propose_changes"],
  "POST /docs/:id/versions/:version/restore": ["propose_changes"],
  "POST /projects": ["create_project"],
  "DELETE /projects/:id": ["propose_changes"],
  // Date fields shown on the calendar (DATA-07) are deadlines get_calendar lists.
  "GET /fields/dates": ["get_calendar"],
  // D4b: a link's hover card and a page's headings and sections are facts
  // fetch returns with the thing; mentions and related pages are found by
  // name and words, as search finds them.
  "GET /links/card": ["fetch"],
  "GET /links/headings": ["fetch"],
  "GET /docs/:id/section": ["fetch"],
  "GET /links/mentions": ["search"],
  "GET /links/related": ["search"],
  // D3a's "Linked here" and D4a's saved views, covered by the agents'
  // get_links, search, query and save_view (A4) now both are merged.
  "GET /links/here": ["get_links"],
  "GET /views": ["search", "fetch"],
  "POST /views": ["save_view"],
  "PUT /views/:id": ["save_view"],
  "DELETE /views/:id": ["propose_changes"],
  "POST /views/run": ["query"],
  // H6a: every feature, no gaps. The agent acts for the person, so it may
  // start a session and say how one went (attributed to it); it changes
  // every planner setting, the time zone, digest emails and notices, keeps
  // originals or not, subscribes to calendars by link (Orbyn's own fetch,
  // with its public-address check) and writes a day's agenda page from the
  // calendar (never the hosted brief).
  "GET /blocks/check-ins": ["get_work_patterns"],
  "POST /blocks/:id/check-in": ["reschedule_sessions"],
  "POST /blocks/:id/start": ["reschedule_sessions"],
  "PUT /planner/prefs": ["update_planner_settings"],
  "POST /me/timezone": ["update_planner_settings"],
  "PUT /me/originals": ["update_planner_settings"],
  "GET /me/calendar-subscriptions": ["get_work_patterns"],
  "POST /me/calendar-subscriptions": ["update_planner_settings"],
  "DELETE /me/calendar-subscriptions/:id": ["update_planner_settings"],
  "POST /agenda/today": ["create_doc"],
  "GET /agenda/today": ["create_doc"],
  "POST /agenda/:date": ["create_doc"],
  // H6b: every feature, no gaps. Pages (other names, folds, linking a
  // mention, moving lines to a new page, merging, taking a source off, the
  // Trash list and bringing a page back), your own fields, pinning and
  // exporting views (CSV as text), milestones and the keep-out switch
  // (switching back in is always asked), running a team (always asked
  // first: team admin and invites are on the ask-first list), a team's
  // recent changes, and changing or refreshing a subscribed calendar.
  "POST /links/mentions/link": ["organize"],
  "POST /docs/:id/extract": ["organize"],
  "POST /docs/:id/merge": ["organize"],
  "PUT /docs/:id/aliases": ["organize"],
  // A page's cover and icon (W6): organize "look".
  "PUT /docs/:id/look": ["organize"],
  "GET /docs/:id/folds": ["fetch"],
  "PUT /docs/:id/folds": ["organize"],
  "DELETE /docs/:id/sources/:sourceId": ["organize"],
  "GET /docs/trash": ["get_history"],
  "POST /docs/:id/restore": ["propose_changes"],
  "PUT /views/:id/pin": ["save_view"],
  "GET /views/:id/export.csv": ["save_view"],
  "GET /fields": ["fetch"],
  "POST /fields": ["organize"],
  "PUT /fields/:id": ["organize"],
  "DELETE /fields/:id": ["propose_changes"],
  "GET /fields/values": ["fetch"],
  "PUT /fields/:id/value": ["organize"],
  "GET /projects/:id/milestones": ["get_project"],
  "POST /projects/:id/milestones": ["update_project"],
  "PUT /projects/:id/milestones/:milestoneId": ["update_project"],
  "DELETE /projects/:id/milestones/:milestoneId": [
    "update_project",
    "propose_changes",
  ],
  "PUT /items/:id/milestone": ["update_project"],
  "PUT /projects/:id/assistant": ["update_project"],
  "POST /teams": ["organize"],
  "PUT /teams/:id": ["organize"],
  "POST /teams/:id/members": ["organize"],
  "DELETE /teams/:id/members/:userId": ["organize"],
  "PUT /teams/:id/members/:userId": ["organize"],
  "PUT /teams/:id/attention": ["organize"],
  "GET /changes": ["get_history"],
  "PUT /me/calendar-subscriptions/:id": ["update_planner_settings"],
  "POST /me/calendar-subscriptions/:id/refresh": ["update_planner_settings"],
  // H8: agents start warm. The "About me for agents" page (read with
  // get_context, made with create_doc kind "profile", changed with
  // edit_doc) and each space's instructions (read with get_context,
  // changed with organize; a team's are asked first).
  "GET /me/agent-context": ["get_context"],
  "DELETE /me/memory/:id": ["manage_memory"],
  // Muse M1: the named agent (read with get_context, changed with update_agent).
  "GET /me/agent": ["get_context"],
  "PUT /me/agent": ["update_agent"],
  "POST /me/agent-profile": ["create_doc"],
  "PUT /me/agent-instructions": ["organize"],
  "PUT /teams/:id/agent-instructions": ["organize"],
};

/** Routes agents never reach, with the reason. */
export const EXCLUDED: Record<string, ExclusionReason> = {
  "POST /recents": "device",
  "GET /admin/agents": "admin",
  "PUT /admin/agents": "admin",
  "GET /admin/agents/clients": "admin",
  "GET /admin/agents/usage": "admin",
  "DELETE /admin/users/:id/agents/:grantId": "admin",
  "GET /admin/analytics": "admin",
  "PUT /admin/announcement": "admin",
  "GET /admin/audit": "admin",
  "GET /admin/database/tables": "admin",
  "GET /admin/database/tables/:name": "admin",
  "GET /admin/database/tables/:name/rows": "admin",
  "GET /admin/legal": "admin",
  "PUT /admin/legal": "admin",
  "PUT /admin/maintenance": "admin",
  "GET /admin/overview": "admin",
  "GET /admin/requests": "admin",
  "GET /admin/requests/summary": "admin",
  "GET /admin/settings": "admin",
  "PUT /admin/settings": "admin",
  "POST /admin/settings/test-email": "admin",
  "GET /admin/storage": "admin",
  "DELETE /admin/storage/files/:importId": "admin",
  "POST /admin/storage/sweep": "admin",
  "GET /admin/sweep": "admin",
  "PUT /admin/sweep/retention": "admin",
  "POST /admin/sweep/run": "admin",
  "GET /admin/teams": "admin",
  "GET /admin/updates": "admin",
  "GET /admin/users": "admin",
  "DELETE /admin/users/:id": "admin",
  "GET /admin/users/:id": "admin",
  "PUT /admin/users/:id": "admin",
  "DELETE /admin/users/:id/api-keys/:keyId": "admin",
  "GET /admin/users/:id/export": "admin",
  "PUT /admin/users/:id/profile": "admin",
  "POST /admin/users/:id/reset-2fa": "admin",
  "POST /admin/users/:id/reset-link": "admin",
  "DELETE /admin/users/:id/sessions/:sessionId": "admin",
  "POST /admin/users/:id/sign-out": "admin",
  "POST /ai/agenda/today": "hosted_ai",
  "POST /ai/chat": "hosted_ai",
  "GET /ai/chat/:id": "hosted_ai",
  "POST /ai/chat/start": "hosted_ai",
  "POST /ai/chat/:id/answer": "assistant_control",
  "POST /ai/chat/:id/approve": "assistant_control",
  "POST /ai/chat/:id/stop": "assistant_control",
  "POST /ai/project": "hosted_ai",
  "POST /ai/proposals/:id/apply": "people_only",
  // The Review inbox and Undo: only the person signed in decides.
  "GET /proposals": "people_only",
  "GET /proposals/count": "people_only",
  "GET /proposals/:id": "people_only",
  "POST /proposals/:id/apply": "people_only",
  "POST /proposals/:id/decline": "people_only",
  "POST /proposals/:id/respond": "people_only",
  "POST /me/agents/activity/:id/undo": "people_only",
  "POST /me/agents/:id/jobs/:job/undo": "people_only",
  // Agent 2 (H0): answering an agent's question is the person's own
  // answer (agents ask with ask_person and read the answer in get_inbox).
  "GET /me/questions": "people_only",
  "POST /me/questions/:id/answer": "people_only",
  // What each connection hears, its wake-up address and the person's
  // standing rules: set by the person (agents read the rules in get_inbox).
  "GET /me/agents/:id/inbox": "credentials",
  "PUT /me/agents/:id/inbox": "credentials",
  "PUT /me/agents/:id/wake": "credentials",
  "DELETE /me/agents/:id/wake": "credentials",
  "POST /me/agents/:id/wake/test": "credentials",
  "GET /me/agent-rules": "credentials",
  "POST /me/agent-rules": "credentials",
  "PUT /me/agent-rules/:id": "credentials",
  "DELETE /me/agent-rules/:id": "credentials",
  "GET /ai/providers": "admin",
  "POST /ai/providers": "admin",
  "DELETE /ai/providers/:id": "admin",
  "PUT /ai/providers/:id": "admin",
  "POST /ai/providers/:id/models": "admin",
  "POST /ai/providers/:id/test": "admin",
  "PUT /ai/settings": "admin",
  "PUT /ai/settings/semantic": "admin",
  "PUT /ai/chats/:id": "hosted_ai",
  "DELETE /ai/chats/:id": "hosted_ai",
  "PATCH /ai/chats/:id": "hosted_ai",
  "POST /ai/chats/:id/save-note": "hosted_ai",
  "GET /me/assistant/ideas": "assistant_control",
  "GET /me/assistant/approval-scopes": "assistant_control",
  "PUT /me/assistant/approval-scopes": "assistant_control",
  // The list of kept originals (files to download); the setting is covered.
  "GET /me/originals": "kept_files",
  "GET /docs/:id/original": "kept_files",
  "DELETE /docs/:id/original": "kept_files",
  "GET /me/mentions": "device",
  "POST /ai/study/cards/:id/explain": "hosted_ai",
  "POST /ai/study/grade": "hosted_ai",
  "POST /ai/study/pages/:id/cards": "hosted_ai",
  "POST /ai/assist": "hosted_ai",
  "POST /auth/logout": "sign_in",
  "POST /auth/resend-verification": "sign_in",
  "GET /bookings/export.csv": "export_file",
  "PROPFIND /dav/*": "caldav",
  "REPORT /dav/cal/default/*": "caldav",
  "DELETE /dav/cal/default/:file": "caldav",
  "GET /dav/cal/default/:file": "caldav",
  "PUT /dav/cal/default/:file": "caldav",
  "DELETE /devices": "device",
  "POST /devices": "device",
  "POST /docs/:id/ask": "hosted_ai",
  "POST /docs/:id/assist": "hosted_ai",
  "GET /docs/:id/export": "export_file",
  "GET /docs/:id/live": "stream",
  "GET /docs/:id/presence": "device",
  "GET /events": "stream",
  "GET /events/docs/:id": "stream",
  "POST /inbound/mail": "internal",
  "POST /mcp": "mcp",
  "DELETE /me": "account",
  "PUT /me": "account",
  "GET /me/2fa": "sign_in",
  "POST /me/2fa/disable": "sign_in",
  "POST /me/2fa/enable": "sign_in",
  "POST /me/2fa/setup": "sign_in",
  "POST /me/agent-keys": "credentials",
  "GET /me/agents": "credentials",
  "DELETE /me/agents/:id": "credentials",
  "GET /me/agents/:id/activity": "credentials",
  "POST /me/agents/:id/restore": "credentials",
  // Connecting an agent (the consent page) and confirming it's you first.
  "POST /oauth/authorize": "credentials",
  "POST /me/reauth": "sign_in",
  "POST /me/reauth/options": "sign_in",
  "GET /me/api-keys": "credentials",
  "POST /me/api-keys": "credentials",
  "DELETE /me/api-keys/:id": "credentials",
  "DELETE /me/calendar-feed": "credentials",
  "GET /me/calendar-feed": "credentials",
  "POST /me/calendar-feed": "credentials",
  "PUT /me/calendar-feed": "credentials",
  "DELETE /me/chat": "credentials",
  "GET /me/chat": "credentials",
  "PUT /me/chat": "credentials",
  "POST /me/chat/test": "credentials",
  "POST /me/consent": "account",
  "GET /me/export": "account",
  "GET /me/export.zip": "account",
  "GET /ai/capabilities": "hosted_ai",
  "POST /capture/preview": "outside_fetch",
  "POST /me/first-run": "account",
  "POST /me/first-run/skip": "account",
  "POST /imports/pages": "bring_in",
  "GET /docs/:id/publish": "publishing",
  "PUT /docs/:id/publish": "publishing",
  "DELETE /docs/:id/publish": "publishing",
  "PUT /docs/:id/web-description": "publishing",
  "GET /folders/:id/publish": "publishing",
  "PUT /folders/:id/publish": "publishing",
  "DELETE /folders/:id/publish": "publishing",
  "GET /teams/:id/publishing": "publishing",
  "PUT /teams/:id/publishing": "team_admin",
  "DELETE /me/inbox": "account",
  "GET /me/inbox": "account",
  "POST /me/inbox/rotate": "account",
  "GET /me/passkeys": "sign_in",
  "POST /me/passkeys": "sign_in",
  "DELETE /me/passkeys/:id": "sign_in",
  "POST /me/passkeys/options": "sign_in",
  "GET /me/privacy": "account",
  "PUT /me/privacy": "account",
  "GET /me/profile": "account",
  "PUT /me/profile": "account",
  "GET /me/reentry": "device",
  "POST /me/reentry/dismiss": "device",
  "GET /me/sessions": "sign_in",
  "DELETE /me/sessions/:id": "sign_in",
  "POST /me/sessions/revoke-others": "sign_in",
  "GET /me/webhooks": "credentials",
  "POST /me/webhooks": "credentials",
  "DELETE /me/webhooks/:id": "credentials",
  "PUT /me/webhooks/:id": "credentials",
  "POST /me/webhooks/:id/test": "credentials",
  "POST /planner/digest/test": "sends_outside",
  "GET /presence/devices": "device",
  "DELETE /presence/devices/:deviceId": "device",
  "POST /presence/heartbeat": "device",
  "POST /presence/leave": "device",
  "GET /presence/settings": "device",
  "PUT /presence/settings": "device",
  "DELETE /teams/:id": "team_admin",
  "PUT /teams/:id/agent-access": "team_admin",
  "GET /teams/:id/agents": "team_admin",
  "GET /teams/:id/presence": "device",
  // Merged in the M1–M4 integration and classified in A1-late.
  "POST /projects/:id/visit": "device",
  "DELETE /docs/:id/forever": "trash",
  // Classified with the toolsets (A5).
  "PUT /me/agents/:id/toolsets": "credentials",
  "PUT /me/agents/:id/trust": "credentials",
  "PUT /items/:id/position": "arrangement",
  // D4b: richer links and pages.
  "POST /docs/:id/anchor": "editor_shortcut",
  "POST /docs/:id/files": "file_bytes",
  "GET /docs/:id/files": "file_bytes",
  "GET /docs/files/:id": "file_bytes",
  "DELETE /docs/files/:id": "file_bytes",
  "GET /files/usage": "file_bytes",
  // Your pictures, to pick a cover from (W6).
  "GET /me/pictures": "file_bytes",
  // D5: later page, navigation and mobile features.
  "GET /me/prefs": "navigation",
  "PUT /me/prefs": "navigation",
  "DELETE /me/prefs": "navigation",
  "GET /starred": "navigation",
  "GET /links/map": "connections_map",
  "PUT /docs/:id/archive": "library",
  "PUT /folders/:id/archive": "library",
  "POST /docs/bulk": "library",
  "GET /teams/:id/policies": "team_admin",
  "PUT /teams/:id/policies": "team_admin",
  "GET /me/clip-keys": "credentials",
  "POST /me/clip-keys": "credentials",
  "DELETE /me/clip-keys/:id": "credentials",
  "GET /clips/destinations": "clipper",
  "POST /clips": "clipper",
  "POST /ai/recordings/:id/summary": "hosted_ai",
};

/**
 * Signed-in routes agents can't reach yet. Empty since A5: every signed-in
 * route is covered by a tool or excluded with a reason, and a new one must
 * be too (the inventory test holds this at zero).
 */
export const PENDING: string[] = [];

/**
 * Routes that answer without signing in: sign-in itself, public pages
 * (booking, invites, RSVP, profiles), the status report and well-known
 * documents. Listed so a new public route is looked at before it ships.
 */
export const PUBLIC: string[] = [
  "GET /maintenance",
  "GET /announcement",
  "POST /auth/register",
  "POST /auth/verify-email",
  "POST /auth/forgot-password",
  "POST /auth/reset-password",
  "POST /auth/login",
  "POST /auth/passkey/options",
  "POST /auth/passkey",
  "GET /legal",
  "GET /legal/:doc",
  "PROPFIND /.well-known/caldav",
  "PROPPATCH /dav/*",
  "MKCALENDAR /dav/*",
  "GET /calendar/feed/:file",
  "GET /openapi.yaml",
  "GET /book/:slug",
  "POST /book/:slug",
  "POST /book/confirm/:token",
  "GET /book/manage/:token",
  "GET /book/manage/:token/slots",
  "POST /book/manage/:token/reschedule",
  "POST /book/manage/:token/cancel",
  "POST /book/cancel/:token",
  "GET /invite/:token",
  "POST /invite/:token",
  "GET /u/:handle",
  "GET /rsvp/:token",
  "POST /rsvp/:token",
  "GET /status",
  "PUT /files/u/:token",
  // Pictures and files in pages: the signed one-time upload link and the
  // signed hour-long link to show or download one (EDT-01).
  "PUT /files/p/:token",
  "GET /files/r/:token",
  // Published pages (SHR-05): read by anyone with the address, with the
  // password form for a page that has one.
  "GET /p/:slug",
  "GET /p/:slug/:doc",
  "POST /p/:slug/unlock",
  "GET /mcp",
  "DELETE /mcp",
  "GET /.well-known/oauth-protected-resource",
  "GET /.well-known/oauth-protected-resource/mcp",
  // Signing in with Orbyn: the authorization server's metadata and the
  // endpoints apps call themselves, and the consent page's check and
  // decline (which only ever send the browser back to an app's own
  // declared address).
  "GET /.well-known/oauth-authorization-server",
  "GET /oauth/authorize/check",
  "POST /oauth/authorize/deny",
  "POST /oauth/token",
  "POST /oauth/revoke",
  "POST /oauth/register",
  "GET /.well-known/*",
  // The developer page's catalog and the security contact (A5).
  "GET /developers/mcp",
  "GET /.well-known/security.txt",
  // The OpenAI apps directory's domain check (A7).
  "GET /.well-known/openai-apps-challenge",
  // The files phones check to open the web app's links in the app.
  "GET /.well-known/apple-app-site-association",
  "GET /.well-known/assetlinks.json",
];
