/**
 * Every signed-in route of the app, and what agents can do about it: a
 * capability that covers it, an exclusion with a reason (things agents must
 * never do, or that make no sense for them), or pending (not yet reachable by
 * agents; each later phase moves routes from PENDING to COVERED). The route
 * inventory test (backend/tests/route-inventory.test.ts) checks this against
 * the routes the app really has, so a new signed-in route fails CI until it
 * is placed here, and PENDING can only shrink.
 *
 * Keys are "METHOD /route/pattern", as Fastify registers them.
 */

/** Why agents never reach a route. */
export const EXCLUSION_REASONS = {
  sign_in:
    "Signing in and how an account signs in (sessions, two-step, passkeys): people only.",
  account:
    "Account settings, privacy, consent, the email-to-task address, export and deleting the account: people only.",
  credentials:
    "Keys, webhooks, chat delivery, calendar feed links and agent connections: an agent must never mint access or send data somewhere new.",
  outside_fetch:
    "Adding or refreshing a subscribed calendar makes Orbyn fetch an outside address.",
  hosted_ai:
    "Orbyn's own assistant: agents bring their own model and never spend the hosted one.",
  people_only:
    "Approving or declining a proposal, and undoing an agent's change: only a person signed in to Orbyn can.",
  admin: "The admin console and AI provider settings.",
  internal: "Service-to-service routes, never for people or agents.",
  caldav: "CalDAV for calendar apps, signed in with a personal API key.",
  stream: "Long-lived event streams (subscriptions/listen arrives in phase 6).",
  mcp: "The MCP address itself.",
  device:
    "Devices, presence and the person's own activity: an agent polling isn't the person being there.",
  export_file: "Files for download (PDF, Word, CSV), not data an agent needs.",
  team_admin:
    "Making, renaming and deleting teams, members, roles and team policies: people only.",
  sends_outside: "Sends an email to test delivery.",
  app_pages:
    "Pages the app writes for itself from the calendar (the daily agenda): agents read them as pages (fetch, query) and write pages of their own instead.",
  trash:
    "The Trash: agents never see trashed pages, and restoring or deleting for good is for people.",
} as const;
export type ExclusionReason = keyof typeof EXCLUSION_REASONS;

/** Routes a capability already covers, with the capabilities that do. */
export const COVERED: Record<string, string[]> = {
  "GET /search": ["search"],
  "GET /items": ["query"],
  "GET /items/:id": ["fetch"],
  "GET /docs": ["query"],
  "GET /docs/:id": ["fetch"],
  "GET /docs/:id/markdown": ["fetch"],
  "GET /projects": ["query"],
  "GET /projects/:id": ["get_project", "fetch"],
  "GET /projects/:id/activity": ["get_project"],
  "GET /calendar": ["get_calendar"],
  "GET /calendar/search": ["get_calendar"],
  "GET /blocks": ["get_calendar"],
  "GET /work-records": ["query"],
  "GET /work-records/:id": ["fetch"],
  "GET /planner/next": ["get_today"],
  "GET /teams": ["get_context"],
  "GET /me": ["get_context"],
  "GET /planner/prefs": ["get_context"],
  "GET /today": ["get_today"],
  // Merged in the M1–M4 integration and classified in A1-late.
  "GET /items/:id/context": ["fetch"],
  "GET /items/:id/sessions": ["fetch"],
  "GET /planned": ["get_today", "get_calendar"],
  "GET /agenda/:date": ["fetch", "query"],
  "GET /projects/:id/planning": ["get_project"],
  "GET /projects/:id/sessions": ["get_project"],
  // Changes (A3): the write tools, through the same services as these routes.
  "POST /items": ["create_tasks"],
  "POST /items/quick": ["create_tasks"],
  "PUT /items/:id": ["update_tasks", "complete_tasks", "link"],
  "PUT /items/:id/project": ["update_tasks", "link"],
  "DELETE /items/:id": ["propose_changes"],
  "POST /items/:id/steps": ["edit_checklist"],
  "PUT /items/:id/steps/:stepId": ["edit_checklist"],
  "DELETE /items/:id/steps/:stepId": ["propose_changes"],
  "POST /blocks": ["schedule_sessions"],
  "PUT /blocks/:id": ["reschedule_sessions"],
  "POST /blocks/:id/reschedule": ["reschedule_sessions"],
  "DELETE /blocks/:id": ["reschedule_sessions"],
  "POST /planner/preview": ["plan_schedule"],
  "POST /planner/plans/:id/apply": ["schedule_sessions"],
  "GET /planner/plans/:id/stale": ["schedule_sessions"],
  "POST /docs": ["create_doc"],
  "PUT /docs/:id": ["edit_doc", "link"],
  "POST /docs/:id/suggestions": ["edit_doc"],
  "DELETE /docs/:id": ["propose_changes"],
  "POST /docs/:id/versions/:version/restore": ["propose_changes"],
  "POST /projects": ["create_project"],
  "DELETE /projects/:id": ["propose_changes"],
};

/** Routes agents never reach, with the reason. */
export const EXCLUDED: Record<string, ExclusionReason> = {
  "GET /admin/agents": "admin",
  "PUT /admin/agents": "admin",
  "GET /admin/agents/clients": "admin",
  "GET /admin/agents/usage": "admin",
  "DELETE /admin/users/:id/agents/:grantId": "admin",
  "GET /admin/analytics": "admin",
  "PUT /admin/announcement": "admin",
  "GET /admin/audit": "admin",
  "GET /admin/database/tables": "admin",
  "GET /admin/database/tables/:name": "admin",
  "GET /admin/database/tables/:name/rows": "admin",
  "GET /admin/legal": "admin",
  "PUT /admin/legal": "admin",
  "PUT /admin/maintenance": "admin",
  "GET /admin/overview": "admin",
  "GET /admin/requests": "admin",
  "GET /admin/requests/summary": "admin",
  "GET /admin/settings": "admin",
  "PUT /admin/settings": "admin",
  "POST /admin/settings/test-email": "admin",
  "GET /admin/storage": "admin",
  "DELETE /admin/storage/files/:importId": "admin",
  "POST /admin/storage/sweep": "admin",
  "GET /admin/sweep": "admin",
  "PUT /admin/sweep/retention": "admin",
  "POST /admin/sweep/run": "admin",
  "GET /admin/teams": "admin",
  "GET /admin/updates": "admin",
  "GET /admin/users": "admin",
  "DELETE /admin/users/:id": "admin",
  "GET /admin/users/:id": "admin",
  "PUT /admin/users/:id": "admin",
  "DELETE /admin/users/:id/api-keys/:keyId": "admin",
  "GET /admin/users/:id/export": "admin",
  "PUT /admin/users/:id/profile": "admin",
  "POST /admin/users/:id/reset-2fa": "admin",
  "POST /admin/users/:id/reset-link": "admin",
  "DELETE /admin/users/:id/sessions/:sessionId": "admin",
  "POST /admin/users/:id/sign-out": "admin",
  "POST /ai/agenda/today": "hosted_ai",
  "POST /ai/chat": "hosted_ai",
  "GET /ai/chat/:id": "hosted_ai",
  "POST /ai/chat/start": "hosted_ai",
  "POST /ai/project": "hosted_ai",
  "POST /ai/proposals/:id/apply": "people_only",
  // The Review inbox and Undo: only the person signed in decides.
  "GET /proposals": "people_only",
  "GET /proposals/count": "people_only",
  "GET /proposals/:id": "people_only",
  "POST /proposals/:id/apply": "people_only",
  "POST /proposals/:id/decline": "people_only",
  "POST /me/agents/activity/:id/undo": "people_only",
  "GET /ai/providers": "admin",
  "POST /ai/providers": "admin",
  "DELETE /ai/providers/:id": "admin",
  "PUT /ai/providers/:id": "admin",
  "POST /ai/providers/:id/models": "admin",
  "POST /ai/providers/:id/test": "admin",
  "PUT /ai/settings": "admin",
  "POST /ai/study/cards/:id/explain": "hosted_ai",
  "POST /ai/study/grade": "hosted_ai",
  "POST /ai/study/pages/:id/cards": "hosted_ai",
  "POST /auth/logout": "sign_in",
  "POST /auth/resend-verification": "sign_in",
  "GET /bookings/export.csv": "export_file",
  "PROPFIND /dav/*": "caldav",
  "REPORT /dav/cal/default/*": "caldav",
  "DELETE /dav/cal/default/:file": "caldav",
  "GET /dav/cal/default/:file": "caldav",
  "PUT /dav/cal/default/:file": "caldav",
  "DELETE /devices": "device",
  "POST /devices": "device",
  "POST /docs/:id/ask": "hosted_ai",
  "POST /docs/:id/assist": "hosted_ai",
  "GET /docs/:id/export": "export_file",
  "GET /docs/:id/live": "stream",
  "GET /docs/:id/presence": "device",
  "GET /events": "stream",
  "GET /events/docs/:id": "stream",
  "POST /inbound/mail": "internal",
  "POST /mcp": "mcp",
  "DELETE /me": "account",
  "PUT /me": "account",
  "GET /me/2fa": "sign_in",
  "POST /me/2fa/disable": "sign_in",
  "POST /me/2fa/enable": "sign_in",
  "POST /me/2fa/setup": "sign_in",
  "POST /me/agent-keys": "credentials",
  "GET /me/agents": "credentials",
  "DELETE /me/agents/:id": "credentials",
  "GET /me/agents/:id/activity": "credentials",
  "POST /me/agents/:id/restore": "credentials",
  // Connecting an agent (the consent page) and confirming it's you first.
  "POST /oauth/authorize": "credentials",
  "POST /me/reauth": "sign_in",
  "POST /me/reauth/options": "sign_in",
  "GET /me/api-keys": "credentials",
  "POST /me/api-keys": "credentials",
  "DELETE /me/api-keys/:id": "credentials",
  "DELETE /me/calendar-feed": "credentials",
  "GET /me/calendar-feed": "credentials",
  "POST /me/calendar-feed": "credentials",
  "PUT /me/calendar-feed": "credentials",
  "POST /me/calendar-subscriptions": "outside_fetch",
  "DELETE /me/calendar-subscriptions/:id": "outside_fetch",
  "PUT /me/calendar-subscriptions/:id": "outside_fetch",
  "POST /me/calendar-subscriptions/:id/refresh": "outside_fetch",
  "DELETE /me/chat": "credentials",
  "GET /me/chat": "credentials",
  "PUT /me/chat": "credentials",
  "POST /me/chat/test": "credentials",
  "POST /me/consent": "account",
  "GET /me/export": "account",
  "GET /me/export.zip": "account",
  "GET /ai/capabilities": "hosted_ai",
  "POST /capture/preview": "outside_fetch",
  "POST /me/import": "account",
  "DELETE /me/inbox": "account",
  "GET /me/inbox": "account",
  "POST /me/inbox/rotate": "account",
  "GET /me/passkeys": "sign_in",
  "POST /me/passkeys": "sign_in",
  "DELETE /me/passkeys/:id": "sign_in",
  "POST /me/passkeys/options": "sign_in",
  "GET /me/privacy": "account",
  "PUT /me/privacy": "account",
  "GET /me/profile": "account",
  "PUT /me/profile": "account",
  "GET /me/reentry": "device",
  "POST /me/reentry/dismiss": "device",
  "GET /me/sessions": "sign_in",
  "DELETE /me/sessions/:id": "sign_in",
  "POST /me/sessions/revoke-others": "sign_in",
  "POST /me/timezone": "account",
  "GET /me/webhooks": "credentials",
  "POST /me/webhooks": "credentials",
  "DELETE /me/webhooks/:id": "credentials",
  "PUT /me/webhooks/:id": "credentials",
  "POST /me/webhooks/:id/test": "credentials",
  "POST /planner/digest/test": "sends_outside",
  "PUT /planner/prefs": "account",
  "GET /presence/devices": "device",
  "DELETE /presence/devices/:deviceId": "device",
  "POST /presence/heartbeat": "device",
  "POST /presence/leave": "device",
  "GET /presence/settings": "device",
  "PUT /presence/settings": "device",
  "POST /teams": "team_admin",
  "DELETE /teams/:id": "team_admin",
  "PUT /teams/:id": "team_admin",
  "PUT /teams/:id/agent-access": "team_admin",
  "GET /teams/:id/agents": "team_admin",
  "PUT /teams/:id/attention": "team_admin",
  "POST /teams/:id/members": "team_admin",
  "DELETE /teams/:id/members/:userId": "team_admin",
  "PUT /teams/:id/members/:userId": "team_admin",
  "GET /teams/:id/presence": "device",
  // Merged in the M1–M4 integration and classified in A1-late.
  "POST /agenda/today": "app_pages",
  "GET /agenda/today": "app_pages",
  "POST /agenda/:date": "app_pages",
  "POST /projects/:id/visit": "device",
  "GET /docs/trash": "trash",
  "POST /docs/:id/restore": "trash",
  "DELETE /docs/:id/forever": "trash",
};

/**
 * Signed-in routes agents can't reach yet. Writes arrive in phase A3 (with
 * review for anything risky), the other toolsets after. This list may only
 * shrink: the inventory test holds its length.
 */
export const PENDING: string[] = [
  // Built alongside A1–A2 on the planning and pages tracks (merged in the
  // M1–M4 integration): the writes, links, tags, templates and history that
  // agents reach in A3–A5.
  "GET /docs/:id/versions/:version/changes",
  "PUT /docs/:id/tags",
  "POST /docs/:id/tags",
  "GET /docs/event-notes",
  "POST /capture",
  "GET /projects/:id/links",
  "POST /projects/:id/links",
  "DELETE /projects/:id/links/:linkId",
  "POST /projects/:id/plan",
  "GET /page-templates",
  "POST /page-templates",
  "PUT /page-templates/:id",
  "DELETE /page-templates/:id",
  "POST /page-templates/from-doc/:id",
  "POST /page-templates/:id/use",

  "GET /asks",
  "POST /asks/:id/reply",
  "POST /asks/:id/settle",
  "GET /availability",
  "POST /blocks/:id/duplicate",
  "GET /booking-pages",
  "POST /booking-pages",
  "DELETE /booking-pages/:id",
  "PUT /booking-pages/:id",
  "GET /booking-pages/:id/bookings",
  "POST /booking-pages/:id/bookings/:bookingId/cancel",
  "GET /bookings",
  "GET /bookings/:id",
  "POST /bookings/:id/approve",
  "POST /bookings/:id/cancel",
  "POST /bookings/:id/decline",
  "PUT /bookings/:id/no-show",
  "PUT /bookings/:id/note",
  "POST /bookings/:id/reschedule",
  "GET /bookings/:id/slots",
  "GET /bookings/stats",
  "GET /docs/:id/comments",
  "POST /docs/:id/comments",
  "DELETE /docs/:id/comments/:commentId",
  "PUT /docs/:id/comments/:commentId",
  "GET /docs/:id/people",
  "POST /docs/:id/review",
  "GET /docs/:id/suggestions",
  "DELETE /docs/:id/suggestions/:sid",
  "POST /docs/:id/suggestions/:sid",
  "POST /docs/:id/tasks",
  "GET /docs/:id/versions",
  "GET /docs/:id/versions/:version",
  "GET /docs/fading",
  "GET /favourites",
  "PUT /favourites",
  "DELETE /focus/current",
  "GET /focus/current",
  "PUT /focus/current",
  "POST /focus/sessions",
  "GET /focus/summary",
  "GET /folders",
  "POST /folders",
  "DELETE /folders/:id",
  "PUT /folders/:id",
  "GET /imports",
  "POST /imports",
  "DELETE /imports/:id",
  "GET /imports/:id",
  "GET /imports/capabilities",
  "GET /items/:id/ask",
  "POST /items/:id/note",
  "PUT /items/:id/position",
  "GET /items/:id/proofs",
  "POST /items/:id/proofs",
  "DELETE /items/:id/proofs/:proofId",
  "POST /items/:id/skip",
  "POST /items/:id/time",
  "POST /items/:id/updates",
  "GET /lists",
  "POST /lists",
  "DELETE /lists/:id",
  "PUT /lists/:id",
  "GET /me/calendar-subscriptions",
  "GET /notifications",
  "POST /notifications/:id/read",
  "GET /open-invites",
  "POST /open-invites",
  "DELETE /open-invites/:id",
  "GET /open-invites/:id",
  "GET /planner/analytics",
  "GET /planner/estimates",
  "GET /planner/frames",
  "POST /planner/frames",
  "DELETE /planner/frames/:id",
  "PUT /planner/frames/:id",
  "POST /planner/frames/:id/skip",
  "POST /planner/frames/:id/unskip",
  "GET /planner/habits",
  "POST /planner/habits",
  "DELETE /planner/habits/:id",
  "PUT /planner/habits/:id",
  "DELETE /planner/habits/blocks/:id",
  "POST /planner/habits/plan",
  "POST /planner/habits/plan/apply",
  "GET /planner/learning",
  "GET /planner/places",
  "POST /planner/places",
  "DELETE /planner/places/:id",
  "PUT /planner/places/:id",
  "GET /planner/plans/:id",
  "PATCH /planner/plans/:id",
  "GET /planner/reality",
  "GET /planner/review",
  "POST /planner/roll-forward",
  "POST /planner/what-if",
  "GET /progress",
  "PUT /projects/:id",
  "GET /projects/:id/time-machine/:eventOrder",
  "GET /projects/:id/time-machine/checkpoints",
  "GET /study",
  "POST /study/cards/:id/review",
  "PUT /study/exams",
  "GET /study/queue",
  "POST /study/revision/apply",
  "POST /study/revision/plan",
  "GET /tags",
  "POST /tags",
  "DELETE /tags/:id",
  "PUT /tags/:id",
  "GET /teams/:id",
  "GET /teams/:id/analytics",
  "GET /teams/:id/attention",
  "POST /teams/:id/attention/check",
  "GET /teams/:id/availability",
  "GET /teams/:id/capacity",
  "GET /teams/:id/suggest",
  "GET /teams/:id/workload",
  "GET /templates",
  "POST /templates",
  "DELETE /templates/:id",
  "PUT /templates/:id",
  "POST /templates/:id/use",
  "POST /templates/from-project/:id",
  "POST /work-records",
  "PUT /work-records/:id",
  "GET /work-records/:id/evidence",
  "POST /work-records/:id/respond",
];

/**
 * Routes that answer without signing in: sign-in itself, public pages
 * (booking, invites, RSVP, profiles), the status report and well-known
 * documents. Listed so a new public route is looked at before it ships.
 */
export const PUBLIC: string[] = [
  "GET /maintenance",
  "GET /announcement",
  "POST /auth/register",
  "POST /auth/verify-email",
  "POST /auth/forgot-password",
  "POST /auth/reset-password",
  "POST /auth/login",
  "POST /auth/passkey/options",
  "POST /auth/passkey",
  "GET /legal",
  "GET /legal/:doc",
  "PROPFIND /.well-known/caldav",
  "PROPPATCH /dav/*",
  "MKCALENDAR /dav/*",
  "GET /calendar/feed/:file",
  "GET /openapi.yaml",
  "GET /book/:slug",
  "POST /book/:slug",
  "POST /book/confirm/:token",
  "GET /book/manage/:token",
  "GET /book/manage/:token/slots",
  "POST /book/manage/:token/reschedule",
  "POST /book/manage/:token/cancel",
  "POST /book/cancel/:token",
  "GET /invite/:token",
  "POST /invite/:token",
  "GET /u/:handle",
  "GET /rsvp/:token",
  "POST /rsvp/:token",
  "GET /status",
  "PUT /files/u/:token",
  "GET /mcp",
  "DELETE /mcp",
  "GET /.well-known/oauth-protected-resource",
  "GET /.well-known/oauth-protected-resource/mcp",
  // Signing in with Orbyn: the authorization server's metadata and the
  // endpoints apps call themselves, and the consent page's check and
  // decline (which only ever send the browser back to an app's own
  // declared address).
  "GET /.well-known/oauth-authorization-server",
  "GET /oauth/authorize/check",
  "POST /oauth/authorize/deny",
  "POST /oauth/token",
  "POST /oauth/revoke",
  "POST /oauth/register",
  "GET /.well-known/*",
];
