import { fail, isPageImage, sniffPageFile, type DocBlock } from "@orbyn/core";
import type { Queryable } from "../../db/pool.js";
import { pageFileReadableBy } from "../../lib/page-file-access.js";

const MAX_IMAGES = 32;
const MAX_IMAGE_BYTES = 4 * 1024 * 1024;
const MAX_TOTAL_BYTES = 8 * 1024 * 1024;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
type ImageRow = { id: string; mime: string; bytes: number };

async function readableImages(db: Queryable, userId: string, ids: string[]) {
  const rows = (
    await db.query<ImageRow>(
      `SELECT f.id, f.mime, f.bytes::float8 AS bytes FROM page_files f
       WHERE f.id = ANY ($2::uuid[]) AND f.status = 'ready'
         AND f.kind = 'image' AND f.doc_id IS NOT NULL
         AND ${pageFileReadableBy("$1")}`,
      [userId, ids],
    )
  ).rows;
  const byId = new Map(rows.map((row) => [row.id, row]));
  if (ids.some((id) => !byId.has(id)))
    fail(404, "A picture on this page is no longer available.");
  return ids.map((id) => byId.get(id)!);
}

/** Load authorized first-party images into an inert, bounded export snapshot. */
export async function exportImages(
  db: Queryable,
  userId: string,
  blocks: DocBlock[],
  options: {
    baseUrl: string;
    /** A signed path generated by the API, never authored document content. */
    readPath: (id: string) => string;
    signal?: AbortSignal;
    fetch?: typeof fetch;
  },
): Promise<{
  fileUrl: (id: string) => string | null;
  /** Recheck permissions and metadata immediately before sending the file. */
  revalidate: () => Promise<void>;
}> {
  const ids = [
    ...new Set(
      blocks.filter((b) => b.type === "image").map((b) => b.file.toLowerCase()),
    ),
  ];
  if (ids.some((id) => !UUID.test(id)))
    fail(404, "A picture on this page is no longer available.");
  if (ids.length > MAX_IMAGES)
    fail(413, "This page has too many pictures to export.");
  const images = new Map<string, string>();
  if (!ids.length) return { fileUrl: () => null, revalidate: async () => {} };
  const rows = await readableImages(db, userId, ids);
  let expectedTotal = 0;
  for (const row of rows) {
    if (!isPageImage(row.mime)) fail(422, "A picture has an unsupported type.");
    if (!Number.isSafeInteger(row.bytes) || row.bytes < 1)
      fail(422, "A picture has invalid file information.");
    expectedTotal += row.bytes;
    if (row.bytes > MAX_IMAGE_BYTES || expectedTotal > MAX_TOTAL_BYTES)
      fail(413, "The pictures on this page are too large to export.");
  }
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 15_000);
  const signal = options.signal
    ? AbortSignal.any([options.signal, controller.signal])
    : controller.signal;
  try {
    const base = new URL(options.baseUrl);
    if (
      !["http:", "https:"].includes(base.protocol) ||
      base.username ||
      base.password
    )
      throw new Error("Invalid file service URL");
    // Sequential reads keep only one active file stream and bound decoded bytes.
    for (const row of rows) {
      signal.throwIfAborted();
      const path = options.readPath(row.id);
      if (!/^\/files\/r\/[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(path))
        throw new Error("Invalid signed file path");
      const url = new URL(path, base);
      if (url.origin !== base.origin) throw new Error("Invalid file origin");
      const response = await (options.fetch ?? fetch)(url, {
        signal,
        redirect: "error",
      });
      if (
        !response.ok ||
        !response.body ||
        response.headers.get("content-type")?.split(";")[0].trim() !== row.mime
      ) {
        await response.body?.cancel();
        throw new Error("File service failed");
      }
      const length = response.headers.get("content-length");
      if (length !== null && Number(length) !== row.bytes) {
        await response.body.cancel();
        throw new Error("File size changed");
      }
      const reader = response.body.getReader();
      const chunks: Buffer[] = [];
      let size = 0;
      try {
        while (true) {
          signal.throwIfAborted();
          const next = await reader.read();
          if (next.done) break;
          size += next.value.byteLength;
          if (size > row.bytes || size > MAX_IMAGE_BYTES)
            throw new Error("File size changed");
          chunks.push(Buffer.from(next.value));
        }
      } finally {
        await reader.cancel();
      }
      const bytes = Buffer.concat(chunks, size);
      if (size !== row.bytes || !sniffPageFile(bytes, row.mime))
        throw new Error("Invalid picture bytes");
      images.set(row.id, `data:${row.mime};base64,${bytes.toString("base64")}`);
    }
  } catch {
    fail(503, "Pictures could not be loaded for export. Try again shortly.");
  } finally {
    clearTimeout(timer);
    controller.abort();
  }
  return {
    fileUrl: (id) => images.get(id.toLowerCase()) ?? null,
    revalidate: async () => {
      const current = await readableImages(db, userId, ids);
      if (
        current.some(
          (row, i) => row.mime !== rows[i].mime || row.bytes !== rows[i].bytes,
        )
      )
        fail(409, "A picture changed. Refresh the page before exporting.");
    },
  };
}
